operands_dict = {'add': '+', 
                 'sub': '-', 
                 'mult': '*', 
                 'div': '/', 
                 'pow': '**', 
                 'cos': 'cos', 
                 'sin': 'sin', 
                 'tan': 'tan', 
                 'sec': 'sec', 
                 'csc': 'csc', 
                 'cot': 'cot', 
                 'cosh': 'cosh', 
                 'sinh': 'sinh', 
                 'tanh': 'tanh', 
                 'sech': 'sech', 
                 'csch': 'csch', 
                 'coth': 'coth', 
                 'exp':'exp', 
                 'sqrt': 'sqrt', 
                 'ln': 'ln'}